name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Send slack message
        id: hello
        uses: ./actions/slack-actions
        with:
          who-to-greet: "Vitalii Parshyn"

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

      - run: echo "🍏 This job's status is ${{ job.status }}."
